#!/bin/bash
# WCGBROWSER
# This is a sample launcher script
# It assumes you've installed wcgbrowser to /usr/local/share
# Edit it to fit your system

cd /usr/local/share/wcgbrowser
which python3 &>>/dev/null
if [ $? -eq 0 ]
then
    python3 browser.py $@
else
    python browser.py $@
fi
